server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: e-learning-app
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
#  jackson:
#    serialization:
#      ORDER_MAP_ENTRIES_BY_KEYS: true

  datasource:
    url: jdbc:mysql://localhost/ela?currentSchema=public
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: ela.contact.vn@gmail.com
    password: Helloela3.
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

mybatis:
  mapper-locations: classpath:repository/*.xml
  type-aliases-package: com.mdd.ela.dto

api:
  prefix: /ela/v1

jwt:
  signer-key: "hRvc9cgVqAb6QgI7lLllt+PoEQ2U9AwlUXvCqB7rBvUsRLpmzdE+/WdbvqfwlJWO"

openapi:
  service:
    api-docs: api-service
    title: ELA API document
    version: v1
    server: http://192.168.0.113:8080

springdoc:
  api-docs:
    path: /ela/v1/api-docs
  swagger-ui:
    path: /ela/swagger-ui.html
