redis:
  host: 127.0.0.1
  port: 6379

spring:
  profiles:
    active: dev

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  flyway:
    locations: classpath:/db/migration, classpath:/dev/db/migration
    baseline-on-migrate: true
    baseline-version: 1

s3:
  access-key: ${S3_ACCESS_KEY}
  secret: ${S3_SECRET}
  region: ${S3_REGION}
  bucket-name: ${S3_BUCKET_NAME}

mybatis:
  mapper-locations: classpath:repository/*.xml
  type-aliases-package: com.mdd.ela.dto

api:
  prefix: /ela/v1

jwt:
  signer-key: ${JWT_SIGNER_KEY}

openapi:
  service:
    api-docs: api-service
    title: ELA API document
    version: v1
    server: http://127.0.0.1:8080

springdoc:
  api-docs:
    path: /ela/v1/api-docs
  swagger-ui:
    path: /ela/swagger-ui.html
