server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: e-learning-app
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  redis:
    host: 127.0.0.1
    port: 6379

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

mybatis:
  mapper-locations: classpath:repository/*.xml
  type-aliases-package: com.mdd.ela.dto

api:
  prefix: /ela/v1

jwt:
  signer-key: ${JWT_SIGNER_KEY}

openapi:
  service:
    api-docs: api-service
    title: ELA API document
    version: v1
    server: http://127.0.0.1:8080

springdoc:
  api-docs:
    path: /ela/v1/api-docs
  swagger-ui:
    path: /ela/swagger-ui.html
